# MNIST 데이터 설명
- https://sdc-james.gitbook.io/onebook/4.-and/5.1./5.1.3.-mnist-dataset

# 이미지 픽셀화 및 CNN학습
- https://rdmkyg.blogspot.com/2021/06/cnn-cat-and-dog-dataset.html
- https://wikidocs.net/61073

In [1]:
import os
import json
import numpy as np
from PIL import Image
import matplotlib.pylab as plt
import cv2
import glob
import torch

In [2]:
import transformers

In [3]:
# one-hot encoding: 60개

In [4]:
image_PATH_dir = 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터'
label_PATH_dir = 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터'

In [5]:
image_data = glob.glob(image_PATH_dir+'\\*.png')
label_data = glob.glob(label_PATH_dir+'\\*.json')

In [6]:
print(image_data[1:5])
print(label_data[1:5])

['D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터\\apple_fuji_L_1-11_1TOP.png', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터\\apple_fuji_L_1-12_2FR45.png', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터\\apple_fuji_L_1-13_3FR90.png', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터\\apple_fuji_L_1-14_4DI45.png']
['D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\apple_fuji_L_1-11_1TOP.json', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\apple_fuji_L_1-12_2FR45.json', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\apple_fuji_L_1-13_3FR90.json', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\apple_fuji_L_1-14_4DI45.json']


# labelling

In [7]:
labelling = []

# a = image_data[0]
a = 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\chinese-cabbage_M_1-4_4DI45'
a = a.split('\\')[4]
print(a)

a = a.split('_')
print(a)

a = a[0] + '_' + a[1] 
print(a)

chinese-cabbage_M_1-4_4DI45
['chinese-cabbage', 'M', '1-4', '4DI45']
chinese-cabbage_M


In [8]:
labelling = []
for i in label_data:
    label = i
    label = label.split('\\')[4]
    label = label.split('_')
    if label[0] == 'chinese-cabbage':
        label = label[0] + '_' + label[1]
        labelling.append(label)
    else:
        label = label[0] + '_' + label[1] + '_' + label[2]
        labelling.append(label)

In [9]:
k = sorted(labelling)
print(len(k))
print(k[0:21])

2380
['apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L']


In [10]:
l = sorted(set(labelling))
print(l)
print(len(l))

['apple_fuji_L', 'apple_fuji_M', 'apple_fuji_S', 'apple_yanggwang_L', 'apple_yanggwang_M', 'apple_yanggwang_S', 'cabbage_green_L', 'cabbage_green_M', 'cabbage_green_S', 'cabbage_red_L', 'cabbage_red_M', 'cabbage_red_S', 'chinese-cabbage_L', 'chinese-cabbage_M', 'chinese-cabbage_S', 'garlic_uiseong_L', 'garlic_uiseong_M', 'garlic_uiseong_S', 'mandarin_hallabong_L', 'mandarine_hallabong_M', 'mandarine_hallabong_S', 'mandarine_onjumilgam_L', 'mandarine_onjumilgam_M', 'mandarine_onjumilgam_S', 'onion_red_L', 'onion_red_M', 'onion_red_S', 'onion_white_L', 'onion_white_M', 'onion_white_S', 'pear_chuhwang_L', 'pear_chuhwang_M', 'pear_chuhwang_S', 'pear_singo_L', 'pear_singo_M', 'pear_singo_S', 'persimmon_bansi_L', 'persimmon_bansi_M', 'persimmon_bansi_S', 'persimmon_booyu_L', 'persimmon_booyu_M', 'persimmon_booyu_S', 'persimmon_daebong_L', 'persimmon_daebong_M', 'persimmon_daebong_S', 'potato_seolbong_L', 'potato_seolbong_M', 'potato_seolbong_S', 'potato_sumi_L', 'potato_sumi_M', 'potato_sumi

In [11]:
labelling = np.array(labelling)

In [12]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text_to_word_sequence(labelling[0])

['apple', 'fuji', 'l']

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [14]:
# 레이블 인코딩
items = labelling
encoder = LabelEncoder()
encoder.fit(items)
labelling = encoder.transform(items)
labels = encoder.inverse_transform(labelling[0:1000])


# 원핫 인코딩
labels = labels.reshape(-1,1)
o_h_encoder = OneHotEncoder()
o_h_encoder.fit(labels)
o_h_labels = o_h_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(o_h_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(o_h_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
원-핫 인코딩 데이터 차원
(1000, 20)


In [15]:
print(type(o_h_labels))

<class 'scipy.sparse.csr.csr_matrix'>


In [19]:
from scipy.sparse import csr_matrix
arr = o_h_labels.toarray()

In [20]:
arr = torch.tensor(arr)

In [21]:
print(type(arr))

<class 'torch.Tensor'>


In [82]:
print(arr[0].shape)

(20,)


# Transferring Image_to_Data

In [22]:
import PIL.Image as pilimg

In [23]:
# Read image
image = []
for j in image_data[0:1000]:
    
    im = pilimg.open(j)

    # Fetch image pixel data to numpy array
    pix = np.array(im)
#     pix = torch.tensor(pix)
#     pix = torch.reshape(pix, (-1,))
    pix = pix / 255
    
    image.append(pix)
    # plt.imshow(pix)
#     print(pix.shape)

In [24]:
image = np.array(image)

In [25]:
print(type(image))

<class 'numpy.ndarray'>


In [26]:
image = image.reshape(1000,3000000)

In [ ]:
# new = torch.tensor(image)

In [54]:
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
import torchvision
from torchvision import transforms

In [44]:
trans = transforms.Compose([transforms.Resize((500,500)), 
                            transforms.ToTensor(),
                            transforms.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5))])
trainset = torchvision.datasets.ImageFolder(root = 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터', transform = trans)

FileNotFoundError: Couldn't find any class folder in D:\DOWNLOAD\2020-02-068.농산물품질_sample\원천데이터.

In [27]:
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split

In [28]:
print(type(image))
print(type(arr))


<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [30]:
X_train, X_test, y_train, y_test = train_test_split(image, k[0:1000], test_size = 1/5, random_state = 0)

# print(X_train)
X_train = torch.Tensor(X_train)
X_test = torch.Tensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

# like zipping

ds_train = TensorDataset(X_train, y_train) # container that binds learning data X and label Y. (only tensor type)
ds_test = TensorDataset(X_test, y_test)

loader_train = DataLoader(ds_train, batch_size = 20, shuffle = True)
loader_test = DataLoader(ds_test, batch_size = 20, shuffle = False)

MemoryError: Unable to allocate 17.9 GiB for an array with shape (800, 3000000) and data type float64

In [ ]:
from torch import nn

model = nn.Sequential()
model.add_module('fc1', nn.Linear(1000*1000*3, 50))
model.add_module('relu1', nn.ReLU())
model.add_module('fc2',nn.Linear(50,25))
model.add_module('relu2', nn.ReLU())
model.add_module('fc3', nn.Linear(25,20))

In [ ]:
from torch import optim

loss_fn = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr = 0.01)

In [ ]:
def train(epoch):
    model.train()
    
    for data, targets in loader_train:
#         print('data')
#         print(data.shape)
#         print('target')
#         print(targets.shape)

        optimizer.zero_grad()
        outputs = model(data)
        loss = loss_fn(outputs, targets)
        loss.backward()
        optimizer.step()
        
        # print("epoch{}: 완료\n".format(epoch))

In [ ]:
def test():
    model.eval()
    correct = 0
    
    with torch.no_grad():
        for data, targets in loader_test:
            
            outputs = model(data)
            _, predicted = torch.max(outputs.data, 1)
            correct += predicted.eq(targets.data.view_as(predicted)).sum()
            
            
    data_num = len(loader_test.dataset)
    print('\n테스트 데이터에서 예측 정확도: {}/{} ({:.0f}%)\n'.format(correct, data_num, 100* correct / data_num))

In [ ]:
test()

In [ ]:
for epoch in range(3):
    train(epoch)
test()

# My Style

In [24]:
class Layer():
    def __init__(self,input_size,output_size):
        
        self.w = np. random.randn(input_size,output_size)
        self.b = np.zeros(output_size)
        self.dydw = None
        self.dydb = 1 
        
    def forward(self,X):
        self.dydw = X.T
        affine = np.dot(X,self.w) + self.b
        
        return affine
    
    def backward(self,dLdy,lr):
        dLdw = np.dot(self.dydw,dLdy)
        dLdb = np.sum(np.dot(dLdy, self.dydb),axis=0)
        
        dLdx = np.dot(dLdy,np.transpose(self.w))
       
        self.w -= lr * dLdw
        
        self.b -= lr * dLdb
        
        return dLdx
        

In [25]:
class Relu():
    def __init__(self):
        self.mask = None
        
    def forward(self,x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
#         print('dout',dout.shape)
#         print('mask',self.mask.shape)
        dout[self.mask]= 0
        #dout * np.where(self.mask==True,1,0)
        return dout * np.where(self.mask == True,1,0)

In [26]:
class Model():
    def __init__(self):
        self.layers = []
        #layer 설정
        self.layer = [3000000]
        L = int(input('Number of Hidden_Layer: '))
        for i in range(L):
            d = int(input('Dimension:'))
            self.layer.append(d)    
        self.length = len(self.layer)
       
        for i in range(self.length-1):
            self.layers.append(Layer(self.layer[i],self.layer[i+1]))
            self.layers.append(Relu())
        self.layers.append(Layer(self.layer[-1],54))
    
    def forward(self,put):
        output = self.layers[0].forward(put)
        for i in range(1,len(self.layers)):            
            output = self.layers[i].forward(output)
        return output
    
    def backward(self, dld_, lr):
        for i in range(self.length-1,0,-1):
            dld_ = self.layers[i*2].backward(dld_, lr)
            dld_ = self.layers[i*2-1].backward(dld_)
        dld_ = self.layers[0].backward(dld_,lr)

        return dld_

In [27]:
class SoftmaxwithLoss:
    def __init__(self):
        self.loss = None
        self.y = None
        self.t = None
        
    def softmax(self,a):
        c = np.max(a,axis=-1,keepdims=True)
        exp_a = np.exp(a-c)
        sum_exp_a = np.sum(exp_a,axis=-1,keepdims=True)
        y = exp_a / sum_exp_a
        
        return y
    
    def cross_entropy_error(self,y,t):
        delta = 1e-13
        return -np.sum(t * np.log(y + delta)) / y.shape[0]
    
    def forward(self,x,t):
        self.t = t
        self.y = self.softmax(x)
        self.loss = self.cross_entropy_error(self.y, self.t)
        return self.loss
    
    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        dx = (self.y - self.t) / batch_size
        
        return dx

In [28]:
def accuracy(pred, target):
    pred = np.argmax(pred, axis=1)
    if target.ndim != 1 :
        target = np.argmax(target,axis=1)
        
    accuracy = np.sum(pred == target) / float(pred.shape[0])
    
    return accuracy

def learning(model,loss_func,X,y, minibatch_size, epoch_size, learning_rate):
    acc_list = []
    
    for e in range(1,epoch_size+1):
        
        combined = list(zip(X, y))
        permut = np.random.permutation(combined)
        X[:], y[:] = zip(*permut)
        
        number_minibatch= np.int(np.ceil(X.shape[0] / minibatch_size))
        
        for n in range(1, number_minibatch+1):

            X_temp=X[minibatch_size * (n-1):minibatch_size*n]
            y_temp=y[minibatch_size * (n-1):minibatch_size*n]
            
            c = model.forward(X_temp)
            J = loss_func.forward(c,y_temp)
        
            dJdh = loss_func.backward()
            model.backward(dJdh,learning_rate)

 
        c = model.forward(X)
        J = loss_func.forward(c,y)


        acc = accuracy(c, y)

        acc_list.append(acc)
        if e % iter_per_epoch == 0:
             print('*************',e,'th epoch *************')
    #             print('최종')
    #             print(J)
             print('정확도')
             print(acc)
        
    return acc_list

In [53]:
model2 = Model()
swl2 = SoftmaxwithLoss()

minibatch_size = 20
iter_per_epoch = 10


epoch_size = int(input('Epeoch_size:'))
train_result2 = learning(model2, swl2, image, arr, minibatch_size, epoch_size, 0.0001)
test_result2 = learning(model2, swl2, image, arr, minibatch_size, epoch_size, 0.0001)
layer2 = [np.max(train_result2),np.max(test_result2)]
#learning(model, swl, x_train, t_train, minibatch_size, epoch_size, 0.0001)

NameError: name 'Model' is not defined

In [118]:
print(image.shape)
print(arr.shape)

(1000, 3000000)
(1000, 20)


In [117]:
arr = np.array(arr)

In [101]:
a =list(zip(image, o_h_labels))

In [103]:
print(a

AttributeError: 'list' object has no attribute 'shape'