# MNIST 데이터 설명
- https://sdc-james.gitbook.io/onebook/4.-and/5.1./5.1.3.-mnist-dataset

# 이미지 픽셀화 및 CNN학습
- https://rdmkyg.blogspot.com/2021/06/cnn-cat-and-dog-dataset.html
- https://wikidocs.net/61073

In [1]:
import os
import json
import numpy as np
from PIL import Image
import matplotlib.pylab as plt
import cv2
import glob
import torch

In [2]:
import transformers

In [3]:
# one-hot encoding: 60개

In [4]:
image_PATH_dir = 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터'
label_PATH_dir = 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터'

In [5]:
image_data = glob.glob(image_PATH_dir+'\\*.png')
label_data = glob.glob(label_PATH_dir+'\\*.json')

In [6]:
print(image_data[1:5])
print(label_data[1:5])

['D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터\\apple_fuji_L_1-11_1TOP.png', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터\\apple_fuji_L_1-12_2FR45.png', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터\\apple_fuji_L_1-13_3FR90.png', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\원천데이터\\apple_fuji_L_1-14_4DI45.png']
['D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\apple_fuji_L_1-11_1TOP.json', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\apple_fuji_L_1-12_2FR45.json', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\apple_fuji_L_1-13_3FR90.json', 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\apple_fuji_L_1-14_4DI45.json']


# labelling

In [7]:
labelling = []

# a = image_data[0]
a = 'D:\\DOWNLOAD\\2020-02-068.농산물품질_sample\\라벨링 데이터\\chinese-cabbage_M_1-4_4DI45'
a = a.split('\\')[4]
print(a)

a = a.split('_')
print(a)

a = a[0] + '_' + a[1] 
print(a)

chinese-cabbage_M_1-4_4DI45
['chinese-cabbage', 'M', '1-4', '4DI45']
chinese-cabbage_M


In [8]:
labelling = []
for i in label_data:
    label = i
    label = label.split('\\')[4]
    label = label.split('_')
    if label[0] == 'chinese-cabbage':
        label = label[0] + '_' + label[1]
        labelling.append(label)
    else:
        label = label[0] + '_' + label[1] + '_' + label[2]
        labelling.append(label)

In [9]:
k = sorted(labelling)
print(len(k))
print(k[0:21])

2380
['apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L', 'apple_fuji_L']


In [47]:
l = sorted(set(labelling))
print(l)
print(len(l))

['apple_fuji_L', 'apple_fuji_M', 'apple_fuji_S', 'apple_yanggwang_L', 'apple_yanggwang_M', 'apple_yanggwang_S', 'cabbage_green_L', 'cabbage_green_M', 'cabbage_green_S', 'cabbage_red_L', 'cabbage_red_M', 'cabbage_red_S', 'chinese-cabbage_L', 'chinese-cabbage_M', 'chinese-cabbage_S', 'garlic_uiseong_L', 'garlic_uiseong_M', 'garlic_uiseong_S', 'mandarin_hallabong_L', 'mandarine_hallabong_M', 'mandarine_hallabong_S', 'mandarine_onjumilgam_L', 'mandarine_onjumilgam_M', 'mandarine_onjumilgam_S', 'onion_red_L', 'onion_red_M', 'onion_red_S', 'onion_white_L', 'onion_white_M', 'onion_white_S', 'pear_chuhwang_L', 'pear_chuhwang_M', 'pear_chuhwang_S', 'pear_singo_L', 'pear_singo_M', 'pear_singo_S', 'persimmon_bansi_L', 'persimmon_bansi_M', 'persimmon_bansi_S', 'persimmon_booyu_L', 'persimmon_booyu_M', 'persimmon_booyu_S', 'persimmon_daebong_L', 'persimmon_daebong_M', 'persimmon_daebong_S', 'potato_seolbong_L', 'potato_seolbong_M', 'potato_seolbong_S', 'potato_sumi_L', 'potato_sumi_M', 'potato_sumi

In [10]:
labelling = np.array(labelling)

In [11]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text_to_word_sequence(labelling[0])

['apple', 'fuji', 'l']

In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [37]:
# 레이블 인코딩
items = labelling
encoder = LabelEncoder()
encoder.fit(items)
labelling = encoder.transform(items)


# 원핫 인코딩
labels = encoder.inverse_transform(labelling)
labels = labels.reshape(-1,1)
o_h_encoder = OneHotEncoder()
o_h_encoder.fit(labels)
o_h_labels = o_h_encoder.transform(labels)

print(set(labelling))
print('원-핫 인코딩 데이터')
print(o_h_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(o_h_labels.shape)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53}
원-핫 인코딩 데이터
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
원-핫 인코딩 데이터 차원
(2380, 54)


In [52]:
print(type(o_h_labels))

<class 'scipy.sparse.csr.csr_matrix'>


In [84]:
from scipy.sparse import csr_matrix
arr = o_h_labels.toarray()

In [85]:
print(arr.shape)
print(type(arr))

(2380, 54)
<class 'numpy.ndarray'>


In [17]:
arr = torch.tensor(arr)

In [54]:
print(type(arr))

<class 'numpy.ndarray'>


In [55]:
print(arr[0].shape)

(14,)


In [15]:
print(len(labelling))

2380


# Transferring Image_to_Data

In [16]:
import PIL.Image as pilimg

In [179]:
# Read image
image = []
for j in image_data:
    
    im = pilimg.open(j)

    # Fetch image pixel data to numpy array
    pix = np.array(im)
#     pix = torch.tensor(pix)
#     pix = torch.reshape(pix, (-1,))
    pix = pix / 255
    
    image.append(pix)
    # plt.imshow(pix)
#     print(pix.shape)

KeyboardInterrupt: 

In [58]:
image = []
for j in image_data:
    # Read image 

    image1 = Image.open(j)
    # plt.imshow(image1)
    # plt.show()
    imag1_size = image1.size
    # print(imag1_size)

    # Resize image
    image1 = image1.resize((int(imag1_size[0]*(0.064)), int(imag1_size[1]*(0.064))))
    imag1_size = image1.size
    # plt.imshow(image1)
    # plt.show()
    # print(imag1_size)
    # Fetch image pixel data to numpy array
    pix = np.array(image1)
    pix = pix / 255
    pix = pix.flatten()

    image.append(pix)


In [59]:
image = np.array(image)

In [60]:
print(type(image))
print(image.shape)

<class 'numpy.ndarray'>
(2380, 12288)


In [44]:
image = image.reshape(2380,12288)

In [61]:
print(image[0])

[0.78431373 0.85490196 0.8627451  ... 0.78431373 0.83921569 0.84705882]


In [46]:
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
import torchvision
from torchvision import transforms

In [47]:
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split

In [48]:
print(type(image))
print(type(labelling))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [62]:
X_train, X_test, y_train, y_test = train_test_split(image, labelling, test_size = 1/7, random_state = 0)

# print(X_train)
X_train = torch.Tensor(X_train)
X_test = torch.Tensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

# like zipping

ds_train = TensorDataset(X_train, y_train) # container that binds learning data X and label Y. (only tensor type)
ds_test = TensorDataset(X_test, y_test)

loader_train = DataLoader(ds_train, batch_size = 20, shuffle = True)
loader_test = DataLoader(ds_test, batch_size = 20, shuffle = False)

In [63]:
from torch import nn

model = nn.Sequential()
model.add_module('fc1', nn.Linear(64*64*3, 100))
model.add_module('relu1', nn.ReLU())
model.add_module('fc2',nn.Linear(100,50))
model.add_module('relu2', nn.ReLU())
model.add_module('fc3', nn.Linear(50,54))

In [64]:
from torch import optim

loss_fn = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr = 0.01)

In [65]:
def train(epoch):
    model.train()
    
    for data, targets in loader_train:
        optimizer.zero_grad()
        outputs = model(data)
        loss = loss_fn(outputs, targets)
        loss.backward()
        optimizer.step()
        
    print("epoch{}: 완료\n".format(epoch))

In [66]:
def test():
    model.eval()
    correct = 0
    
    with torch.no_grad():
        for data, targets in loader_test:
            
            outputs = model(data)
            _, predicted = torch.max(outputs.data, 1)
            correct += predicted.eq(targets.data.view_as(predicted)).sum()
            
            
    data_num = len(loader_test.dataset)
    print('\n테스트 데이터에서 예측 정확도: {}/{} ({:.0f}%)\n'.format(correct, data_num, 100 * correct / data_num))

In [67]:
test()


테스트 데이터에서 예측 정확도: 11/340 (3%)



In [68]:
for epoch in range(3):
    train(epoch)
test()

epoch0: 완료

epoch1: 완료

epoch2: 완료


테스트 데이터에서 예측 정확도: 7/340 (2%)

